name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@master
      with: 
        repository: GoLP-IST/osiris-tools
        token: ${{ secrets.OS_TOOLS }}
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
